name: firebasetesting
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  bloc: ^8.0.2
  bottom_navy_bar: ^6.0.0
  cloud_firestore: ^3.1.9
  firebase_auth: ^3.3.7
  firebase_core: ^1.12.0
  firebase_messaging: ^11.2.8
  firebase_storage: ^10.2.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  http: ^0.13.4
  image_picker: ^0.8.4+11
  intl: ^0.17.0
  uuid: ^3.0.6

dev_dependencies:
  bloc_test: ^9.0.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
